# Generated by Django 4.2.7 on 2023-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания.', verbose_name='Дата создания')),
                ('income', models.BigIntegerField(default=0, help_text='Сумма дохода на балансе.', verbose_name='Доход')),
                ('expenses', models.BigIntegerField(default=0, help_text='Сумма расходов на балансе.', verbose_name='Расходы')),
                ('balance', models.BigIntegerField(default=0, help_text='Общий баланс, равный доходам минус расходы.', verbose_name='Баланс')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи в балансе.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания.', verbose_name='Дата создания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания.', verbose_name='Дата создания')),
                ('user_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram.', unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя в Telegram.', max_length=120, null=True, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, help_text='Код языка, используемый пользователем в Telegram.', max_length=10, null=True, verbose_name='Код языка')),
                ('is_bot', models.BooleanField(default=False, help_text='Указывает, является ли пользователь ботом.', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
