# Generated by Django 4.2.7 on 2023-12-16 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_remove_telegramchat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Временная метка, указывающая, когда был создан пользователь.', verbose_name='Создан'),
        ),
    ]
