# Generated by Django 4.2.7 on 2023-12-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_alter_telegramuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambalance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата и время создания записи в балансе.', verbose_name='Дата создания'),
        ),
    ]
