# Generated by Django 4.2.7 on 2023-12-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_alter_telegrambalance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Сумма расхода.', verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан расход.', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Расход Telegram',
                'verbose_name_plural': 'Расходы Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Сумма дохода.', verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан доход.', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Доход Telegram',
                'verbose_name_plural': 'Доходы Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TelegramBalance',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.BigIntegerField(default=0, help_text='Баланс пользователя.', verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан пользователь.', verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='telegramincome',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит доход.', on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='telegramexpense',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит расход.', on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
