# Generated by Django 4.2.7 on 2023-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_telegramexpense_telegramincome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramexpense',
            name='amount',
            field=models.BigIntegerField(default=0, help_text='Сумма расхода.', verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='telegramincome',
            name='amount',
            field=models.BigIntegerField(default=0, help_text='Сумма дохода.', verbose_name='Сумма'),
        ),
    ]
