# Generated by Django 4.2.7 on 2023-12-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0007_alter_telegramexpense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Сообщение пользователя.', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан расход.', verbose_name='Создан')),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит расход.', on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поддержка Telegram',
                'verbose_name_plural': 'Поддержка Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
