# Generated by Django 4.2.7 on 2023-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0008_telegramsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chart',
            field=models.FileField(blank=True, help_text='Файл с графиком пользователя.', null=True, upload_to='chart/', verbose_name='График'),
        ),
    ]
